### ISSUE TITLE
Errors in HA System/Core log

### ISSUE THREAD

**Issue by gj52** [hassio-addons/addon-phpmyadmin#15]
# Problem/Motivation

Errors in HA System/Core log
Histgrams don't work
MariaDb 2.1.2

## Actual behavior

  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_clauseelement
    distilled_params,
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1324, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1518, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1284, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 590, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.7/site-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.7/site-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/usr/local/lib/python3.7/site-packages/MySQLdb/connections.py", line 239, in query
    _mysql.connection.query(self, query)
sqlalchemy.exc.OperationalError: (MySQLdb._exceptions.OperationalError) (1927, 'Connection was killed')
[SQL: SELECT 1]
(Background on this error at: http://sqlalche.me/e/e3q8)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 752, in _rollback_impl
    self.engine.dialect.do_rollback(self.connection)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/dialects/mysql/base.py", line 2351, in do_rollback
    dbapi_connection.rollback()
MySQLdb._exceptions.OperationalError: (2006, 'MySQL server has gone away')
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/recorder/__init__.py", line 466, in _reopen_event_session
    self.event_session.rollback()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1006, in rollback
    self.transaction.rollback()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 574, in rollback
    util.raise_(rollback_err[1], with_traceback=rollback_err[2])
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 534, in rollback
    t[1].rollback()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1760, in rollback
    self._do_rollback()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1798, in _do_rollback
    self.connection._rollback_impl()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 754, in _rollback_impl
    self._handle_dbapi_exception(e, None, None, None, None)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1518, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 752, in _rollback_impl
    self.engine.dialect.do_rollback(self.connection)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/dialects/mysql/base.py", line 2351, in do_rollback
    dbapi_connection.rollback()
sqlalchemy.exc.OperationalError: (MySQLdb._exceptions.OperationalError) (2006, 'MySQL server has gone away')
(Background on this error at: http://sqlalche.me/e/e3q8)
2020-06-14 21:08:41 ERROR (SyncWorker_11) [homeassistant.components.sql.sensor] Error executing query SELECT SUM(ROUND(((DATA_LENGTH + INDEX_LENGTH) / 1024 / 1024), 2)) AS "dbsize" FROM INFORMATION_SCHEMA.TABLES LIMIT 1;: (MySQLdb._exceptions.OperationalError) (1927, 'Connection was killed')
[SQL: SELECT SUM(ROUND(((DATA_LENGTH + INDEX_LENGTH) / 1024 / 1024), 2)) AS "dbsize" FROM INFORMATION_SCHEMA.TABLES LIMIT 1;]
(Background on this error at: http://sqlalche.me/e/e3q8)
2020-06-14 21:08:41 ERROR (SyncWorker_11) [sqlalchemy.pool.impl.QueuePool] Exception during reset or similar
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 752, in _rollback_impl
    self.engine.dialect.do_rollback(self.connection)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/dialects/mysql/base.py", line 2351, in do_rollback
    dbapi_connection.rollback()
MySQLdb._exceptions.OperationalError: (2006, 'MySQL server has gone away')
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 697, in _finalize_fairy
    fairy._reset(pool)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 891, in _reset
    self._reset_agent.rollback()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1760, in rollback
    self._do_rollback()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1798, in _do_rollback
    self.connection._rollback_impl()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 754, in _rollback_impl
    self._handle_dbapi_exception(e, None, None, None, None)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1518, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 752, in _rollback_impl
    self.engine.dialect.do_rollback(self.connection)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/dialects/mysql/base.py", line 2351, in do_rollback
    dbapi_connection.rollback()
sqlalchemy.exc.OperationalError: (MySQLdb._exceptions.OperationalError) (2006, 'MySQL server has gone away')
(Background on this error at: http://sqlalche.me/e/e3q8)

<blockquote><img src="//www.sqlalchemy.org/favicon.ico" width="48" align="right"><div><strong><a href="http://sqlalche.me/e/e3q8">Error Messages
 —
    SQLAlchemy 1.3 Documentation</a></strong></div></blockquote>
<blockquote><img src="//www.sqlalchemy.org/favicon.ico" width="48" align="right"><div><strong><a href="http://sqlalche.me/e/e3q8">Error Messages
 —
    SQLAlchemy 1.3 Documentation</a></strong></div></blockquote>
<blockquote><img src="//www.sqlalchemy.org/favicon.ico" width="48" align="right"><div><strong><a href="http://sqlalche.me/e/e3q8">Error Messages
 —
    SQLAlchemy 1.3 Documentation</a></strong></div></blockquote>
<blockquote><img src="//www.sqlalchemy.org/favicon.ico" width="48" align="right"><div><strong><a href="http://sqlalche.me/e/e3q8">Error Messages
 —
    SQLAlchemy 1.3 Documentation</a></strong></div></blockquote>

**Comment by frenck** [comment]
This is not related to this add-on in any way. Please report the issue with Home Assistant.
